---
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/docker-swarm/docker-compose.yml
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
- name: Deploy the Docker Swarm stack using command
  ansible.builtin.command: >
    docker stack deploy -c /opt/docker-swarm/docker-compose.yml qasmat
